version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "jamesjarvis"
  - package-ecosystem: "npm"
    directory: "/monzo-users-graph"
    schedule:
      interval: "monthly"
    assignees:
      - "jamesjarvis"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "jamesjarvis"
